name: KegeCommandSpy
main: com.kegekiss.kegecommandspy.KegeCommandSpy
version: 1.0
author: Kegekiss
commands:
   commandspy:
      description: Permet d'utiliser l'espion des commandes.
      usage: /commandspy [toggle on/off]
      permission: kegecommandspy.command
      permission-message: ยง6Vous n'avez pas la permission d'utiliser cette commande!

permissions:
    kegecommandspy.command:
        description: Permet d'utiliser la commande /commandspy.
        default: op
